### ISSUE TITLE
(Trac #234) test failure on Fedora in test_tub.CancelPendingDeliveries.test_cancel_pending_deliveries

### ISSUE THREAD

**Issue by foolscap-trac** [foolscap-trac/test-foolscap-import-5#230]
| <img alt="davidsarah's avatar" src="https://avatars.githubusercontent.com/u/643204?v=4" width="50" height="50"> | trac:davidsarah reported |
|-|-|
| Trac ID | trac#234 |
| Type | defect |
| Created | 2015-04-22 09:21:24Z |
| Cc | trac:davidsarah |
| Version | 0.6.4 |
| Keywords | test |
| Resolution | fixed |

See https://bugzilla.redhat.com/show_bug.cgi?id=1106775. Almost all of the test failures there are due to #142, except for this one:
```

[ERROR]
Traceback (most recent call last):
  File "/builddir/build/BUILD/foolscap-0.6.4/foolscap/test/test_tub.py", line 386, in tearDown
    if self.tubA.running:
exceptions.AttributeError: 'CancelPendingDeliveries' object has no attribute 'tubA'
foolscap.test.test_tub.CancelPendingDeliveries.test_cancel_pending_deliveries
==================================
```
